cc_binary(
  name = "hello_world",
  deps = ["@com_google_absl//absl/strings"],
  srcs = ["hello_world.cc"]
)

cc_binary(
  name = "print_my_pb",
  deps = ["//proto:addressbook_cc_proto"],
  srcs = ["print_my_pb.cc"]
)